name: Deploy to Streamlit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy Streamlit App to Streamlit Cloud
        run: |
          echo "MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }},
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }},
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}},
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL}},
          CLIENT_ID: ${{ secrets.CLIENT_ID }},
          AUTH_URI: ${{ secrets.AUTH_URI }},
          TOKEN_URI: ${{ secrets.TOKEN_URI }},
          AUTH_PROVIDER_URL: ${{ secrets.AUTH_PROVIDER_URL }},
          CLIENT_CERT_URL: ${{ secrets.CLIENT_CERT_URL }}" > .env
          streamlit run campaign_manager_tool.py --server.port 8501
